# docker-compose.yml
version: '3.7'
services:
  glance:
    image: glanceapp/glance:v0.7.13
    volumes:
      - ./config:/app/config
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Zurich
      - PUID=3000
      - PGID=3000
      - IMMICH_API_KEY=abcd
      - ADGUARD_PASSWORD=efgh
    dns:
      - 1.1.1.1
    restart: unless-stopped
