version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: deepskinai
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
